//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semantika.EuropeanaInside.Eck {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Xsds {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Xsds() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Semantika.EuropeanaInside.Eck.Xsds", typeof(Xsds).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Copyright 2007-2012 The Europeana Foundation Licenced under the EUPL, 
        ///	Version 1.1 (the &quot;Licence&quot;) and subsequent versions as approved by the European 
        ///	Commission; You may not use this work except in compliance with the Licence. 
        ///	You may obtain a copy of the Licence at: http://joinup.ec.europa.eu/software/page/eupl 
        ///	Unless required by applicable law or agreed to in writing, software distributed 
        ///	under the Licence is distributed on an &quot;AS IS&quot; basis, with [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Edm {
            get {
                return ResourceManager.GetString("Edm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsd:schema xmlns:doc=&quot;http://www.mda.org.uk/spectrumXML/Documentation&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; xmlns:lido=&quot;http://www.lido-schema.org&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xml=&quot;http://www.w3.org/XML/1998/namespace&quot; targetNamespace=&quot;http://www.lido-schema.org&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;qualified&quot;&gt;
        ///	&lt;!--  
        ///	xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        ///		xx LI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lido {
            get {
                return ResourceManager.GetString("Lido", resourceCulture);
            }
        }
    }
}
