using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace com.test
{
    using System.Xml.Serialization;
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/1999/02/22-rdf-syntax-ns#")]
    [System.Xml.Serialization.XmlRootAttribute("rights", Namespace = "http://purl.org/dc/elements/1.1/", IsNullable = false)]
    public partial class ResourceOrLiteralType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string langField;

        private string resourceField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string resource
        {
            get
            {
                return this.resourceField;
            }
            set
            {
                this.resourceField = value;
                this.RaisePropertyChanged("resource");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/1999/02/22-rdf-syntax-ns#")]
    [System.Xml.Serialization.XmlRootAttribute("identifier", Namespace = "http://purl.org/dc/elements/1.1/", IsNullable = false)]
    public partial class LiteralType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string langField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
                this.RaisePropertyChanged("lang");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/1999/02/22-rdf-syntax-ns#")]
    [System.Xml.Serialization.XmlRootAttribute("aggregatedCHO", Namespace = "http://www.europeana.eu/schemas/edm/", IsNullable = false)]
    public partial class ResourceType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string resourceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "anyURI")]
        public string resource
        {
            get
            {
                return this.resourceField;
            }
            set
            {
                this.resourceField = value;
                this.RaisePropertyChanged("resource");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.europeana.eu/schemas/edm/")]
    [System.Xml.Serialization.XmlRootAttribute("ugc", Namespace = "http://www.europeana.eu/schemas/edm/", IsNullable = false)]
    public enum UGCType
    {

        /// <remarks/>
        @true,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.w3.org/2004/02/skos/core#")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.w3.org/2004/02/skos/core#", IsNullable = false)]
    public partial class Concept : AboutType
    {

        private object[] itemsField;

        private ItemsChoiceType1[] itemsElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("altLabel", typeof(LiteralType))]
        [System.Xml.Serialization.XmlElementAttribute("broadMatch", typeof(ResourceType))]
        [System.Xml.Serialization.XmlElementAttribute("broader", typeof(ResourceType))]
        [System.Xml.Serialization.XmlElementAttribute("closeMatch", typeof(ResourceType))]
        [System.Xml.Serialization.XmlElementAttribute("exactMatch", typeof(ResourceType))]
        [System.Xml.Serialization.XmlElementAttribute("inScheme", typeof(ResourceType))]
        [System.Xml.Serialization.XmlElementAttribute("narrowMatch", typeof(ResourceType))]
        [System.Xml.Serialization.XmlElementAttribute("narrower", typeof(ResourceType))]
        [System.Xml.Serialization.XmlElementAttribute("notation", typeof(LiteralType))]
        [System.Xml.Serialization.XmlElementAttribute("note", typeof(LiteralType))]
        [System.Xml.Serialization.XmlElementAttribute("prefLabel", typeof(LiteralType))]
        [System.Xml.Serialization.XmlElementAttribute("related", typeof(ResourceType))]
        [System.Xml.Serialization.XmlElementAttribute("relatedMatch", typeof(ResourceType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
                this.RaisePropertyChanged("ItemsElementName");
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/2004/02/skos/core#", IncludeInSchema = false)]
    public enum ItemsChoiceType1
    {

        /// <remarks/>
        altLabel,

        /// <remarks/>
        broadMatch,

        /// <remarks/>
        broader,

        /// <remarks/>
        closeMatch,

        /// <remarks/>
        exactMatch,

        /// <remarks/>
        inScheme,

        /// <remarks/>
        narrowMatch,

        /// <remarks/>
        narrower,

        /// <remarks/>
        notation,

        /// <remarks/>
        note,

        /// <remarks/>
        prefLabel,

        /// <remarks/>
        related,

        /// <remarks/>
        relatedMatch,
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WebResourceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeSpanType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PlaceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AgentType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EuropeanaType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseProvidedCHOType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProvidedCHOType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/1999/02/22-rdf-syntax-ns#")]
    public partial class AboutType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string aboutField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "anyURI")]
        public string about
        {
            get
            {
                return this.aboutField;
            }
            set
            {
                this.aboutField = value;
                this.RaisePropertyChanged("about");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.europeana.eu/schemas/edm/")]
    public partial class WebResourceType : AboutType
    {

        private ResourceOrLiteralType[] descriptionField;

        private ResourceOrLiteralType[] formatField;

        private ResourceOrLiteralType[] rightsField;

        private ResourceOrLiteralType[] sourceField;

        private ResourceOrLiteralType[] conformsToField;

        private ResourceOrLiteralType[] createdField;

        private ResourceOrLiteralType[] extentField;

        private ResourceOrLiteralType[] hasPartField;

        private ResourceOrLiteralType[] isFormatOfField;

        private ResourceOrLiteralType[] issuedField;

        private ResourceType isNextInSequenceField;

        private ResourceOrLiteralType rights1Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("description", Namespace = "http://purl.org/dc/elements/1.1/")]
        public ResourceOrLiteralType[] description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("format", Namespace = "http://purl.org/dc/elements/1.1/")]
        public ResourceOrLiteralType[] format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
                this.RaisePropertyChanged("format");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rights", Namespace = "http://purl.org/dc/elements/1.1/")]
        public ResourceOrLiteralType[] rights
        {
            get
            {
                return this.rightsField;
            }
            set
            {
                this.rightsField = value;
                this.RaisePropertyChanged("rights");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("source", Namespace = "http://purl.org/dc/elements/1.1/")]
        public ResourceOrLiteralType[] source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
                this.RaisePropertyChanged("source");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("conformsTo", Namespace = "http://purl.org/dc/terms/")]
        public ResourceOrLiteralType[] conformsTo
        {
            get
            {
                return this.conformsToField;
            }
            set
            {
                this.conformsToField = value;
                this.RaisePropertyChanged("conformsTo");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("created", Namespace = "http://purl.org/dc/terms/")]
        public ResourceOrLiteralType[] created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
                this.RaisePropertyChanged("created");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("extent", Namespace = "http://purl.org/dc/terms/")]
        public ResourceOrLiteralType[] extent
        {
            get
            {
                return this.extentField;
            }
            set
            {
                this.extentField = value;
                this.RaisePropertyChanged("extent");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("hasPart", Namespace = "http://purl.org/dc/terms/")]
        public ResourceOrLiteralType[] hasPart
        {
            get
            {
                return this.hasPartField;
            }
            set
            {
                this.hasPartField = value;
                this.RaisePropertyChanged("hasPart");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("isFormatOf", Namespace = "http://purl.org/dc/terms/")]
        public ResourceOrLiteralType[] isFormatOf
        {
            get
            {
                return this.isFormatOfField;
            }
            set
            {
                this.isFormatOfField = value;
                this.RaisePropertyChanged("isFormatOf");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("issued", Namespace = "http://purl.org/dc/terms/")]
        public ResourceOrLiteralType[] issued
        {
            get
            {
                return this.issuedField;
            }
            set
            {
                this.issuedField = value;
                this.RaisePropertyChanged("issued");
            }
        }

        /// <remarks/>
        public ResourceType isNextInSequence
        {
            get
            {
                return this.isNextInSequenceField;
            }
            set
            {
                this.isNextInSequenceField = value;
                this.RaisePropertyChanged("isNextInSequence");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rights")]
        public ResourceOrLiteralType rights1
        {
            get
            {
                return this.rights1Field;
            }
            set
            {
                this.rights1Field = value;
                this.RaisePropertyChanged("rights1");
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.europeana.eu/schemas/edm/")]
    public partial class TimeSpanType : AboutType
    {

        private LiteralType[] prefLabelField;

        private LiteralType[] altLabelField;

        private LiteralType[] noteField;

        private ResourceOrLiteralType[] hasPartField;

        private ResourceOrLiteralType[] isPartOfField;

        private LiteralType beginField;

        private LiteralType endField;

        private ResourceType[] sameAsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("prefLabel", Namespace = "http://www.w3.org/2004/02/skos/core#")]
        public LiteralType[] prefLabel
        {
            get
            {
                return this.prefLabelField;
            }
            set
            {
                this.prefLabelField = value;
                this.RaisePropertyChanged("prefLabel");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("altLabel", Namespace = "http://www.w3.org/2004/02/skos/core#")]
        public LiteralType[] altLabel
        {
            get
            {
                return this.altLabelField;
            }
            set
            {
                this.altLabelField = value;
                this.RaisePropertyChanged("altLabel");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("note", Namespace = "http://www.w3.org/2004/02/skos/core#")]
        public LiteralType[] note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
                this.RaisePropertyChanged("note");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("hasPart", Namespace = "http://purl.org/dc/terms/")]
        public ResourceOrLiteralType[] hasPart
        {
            get
            {
                return this.hasPartField;
            }
            set
            {
                this.hasPartField = value;
                this.RaisePropertyChanged("hasPart");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("isPartOf", Namespace = "http://purl.org/dc/terms/")]
        public ResourceOrLiteralType[] isPartOf
        {
            get
            {
                return this.isPartOfField;
            }
            set
            {
                this.isPartOfField = value;
                this.RaisePropertyChanged("isPartOf");
            }
        }

        /// <remarks/>
        public LiteralType begin
        {
            get
            {
                return this.beginField;
            }
            set
            {
                this.beginField = value;
                this.RaisePropertyChanged("begin");
            }
        }

        /// <remarks/>
        public LiteralType end
        {
            get
            {
                return this.endField;
            }
            set
            {
                this.endField = value;
                this.RaisePropertyChanged("end");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sameAs", Namespace = "http://www.w3.org/2002/07/owl#")]
        public ResourceType[] sameAs
        {
            get
            {
                return this.sameAsField;
            }
            set
            {
                this.sameAsField = value;
                this.RaisePropertyChanged("sameAs");
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.europeana.eu/schemas/edm/")]
    public partial class PlaceType : AboutType
    {

        private float latField;

        private bool latFieldSpecified;

        private float longField;

        private bool longFieldSpecified;

        private float altField;

        private bool altFieldSpecified;

        private LiteralType[] prefLabelField;

        private LiteralType[] altLabelField;

        private LiteralType[] noteField;

        private ResourceOrLiteralType[] hasPartField;

        private ResourceOrLiteralType[] isPartOfField;

        private ResourceType[] sameAsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.w3.org/2003/01/geo/wgs84_pos#")]
        public float lat
        {
            get
            {
                return this.latField;
            }
            set
            {
                this.latField = value;
                this.RaisePropertyChanged("lat");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool latSpecified
        {
            get
            {
                return this.latFieldSpecified;
            }
            set
            {
                this.latFieldSpecified = value;
                this.RaisePropertyChanged("latSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.w3.org/2003/01/geo/wgs84_pos#")]
        public float @long
        {
            get
            {
                return this.longField;
            }
            set
            {
                this.longField = value;
                this.RaisePropertyChanged("long");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool longSpecified
        {
            get
            {
                return this.longFieldSpecified;
            }
            set
            {
                this.longFieldSpecified = value;
                this.RaisePropertyChanged("longSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.w3.org/2003/01/geo/wgs84_pos#")]
        public float alt
        {
            get
            {
                return this.altField;
            }
            set
            {
                this.altField = value;
                this.RaisePropertyChanged("alt");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool altSpecified
        {
            get
            {
                return this.altFieldSpecified;
            }
            set
            {
                this.altFieldSpecified = value;
                this.RaisePropertyChanged("altSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("prefLabel", Namespace = "http://www.w3.org/2004/02/skos/core#")]
        public LiteralType[] prefLabel
        {
            get
            {
                return this.prefLabelField;
            }
            set
            {
                this.prefLabelField = value;
                this.RaisePropertyChanged("prefLabel");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("altLabel", Namespace = "http://www.w3.org/2004/02/skos/core#")]
        public LiteralType[] altLabel
        {
            get
            {
                return this.altLabelField;
            }
            set
            {
                this.altLabelField = value;
                this.RaisePropertyChanged("altLabel");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("note", Namespace = "http://www.w3.org/2004/02/skos/core#")]
        public LiteralType[] note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
                this.RaisePropertyChanged("note");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("hasPart", Namespace = "http://purl.org/dc/terms/")]
        public ResourceOrLiteralType[] hasPart
        {
            get
            {
                return this.hasPartField;
            }
            set
            {
                this.hasPartField = value;
                this.RaisePropertyChanged("hasPart");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("isPartOf", Namespace = "http://purl.org/dc/terms/")]
        public ResourceOrLiteralType[] isPartOf
        {
            get
            {
                return this.isPartOfField;
            }
            set
            {
                this.isPartOfField = value;
                this.RaisePropertyChanged("isPartOf");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sameAs", Namespace = "http://www.w3.org/2002/07/owl#")]
        public ResourceType[] sameAs
        {
            get
            {
                return this.sameAsField;
            }
            set
            {
                this.sameAsField = value;
                this.RaisePropertyChanged("sameAs");
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.europeana.eu/schemas/edm/")]
    public partial class AgentType : AboutType
    {

        private LiteralType[] prefLabelField;

        private LiteralType[] altLabelField;

        private LiteralType[] noteField;

        private ResourceOrLiteralType[] dateField;

        private LiteralType[] identifierField;

        private LiteralType beginField;

        private LiteralType endField;

        private LiteralType[] hasMetField;

        private ResourceOrLiteralType[] isRelatedToField;

        private LiteralType[] nameField;

        private LiteralType biographicalInformationField;

        private LiteralType dateOfBirthField;

        private LiteralType dateOfDeathField;

        private LiteralType dateOfEstablishmentField;

        private LiteralType dateOfTerminationField;

        private LiteralType genderField;

        private ResourceOrLiteralType professionOrOccupationField;

        private ResourceType[] sameAsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("prefLabel", Namespace = "http://www.w3.org/2004/02/skos/core#")]
        public LiteralType[] prefLabel
        {
            get
            {
                return this.prefLabelField;
            }
            set
            {
                this.prefLabelField = value;
                this.RaisePropertyChanged("prefLabel");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("altLabel", Namespace = "http://www.w3.org/2004/02/skos/core#")]
        public LiteralType[] altLabel
        {
            get
            {
                return this.altLabelField;
            }
            set
            {
                this.altLabelField = value;
                this.RaisePropertyChanged("altLabel");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("note", Namespace = "http://www.w3.org/2004/02/skos/core#")]
        public LiteralType[] note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
                this.RaisePropertyChanged("note");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("date", Namespace = "http://purl.org/dc/elements/1.1/")]
        public ResourceOrLiteralType[] date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("identifier", Namespace = "http://purl.org/dc/elements/1.1/")]
        public LiteralType[] identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
                this.RaisePropertyChanged("identifier");
            }
        }

        /// <remarks/>
        public LiteralType begin
        {
            get
            {
                return this.beginField;
            }
            set
            {
                this.beginField = value;
                this.RaisePropertyChanged("begin");
            }
        }

        /// <remarks/>
        public LiteralType end
        {
            get
            {
                return this.endField;
            }
            set
            {
                this.endField = value;
                this.RaisePropertyChanged("end");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("hasMet")]
        public LiteralType[] hasMet
        {
            get
            {
                return this.hasMetField;
            }
            set
            {
                this.hasMetField = value;
                this.RaisePropertyChanged("hasMet");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("isRelatedTo")]
        public ResourceOrLiteralType[] isRelatedTo
        {
            get
            {
                return this.isRelatedToField;
            }
            set
            {
                this.isRelatedToField = value;
                this.RaisePropertyChanged("isRelatedTo");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("name", Namespace = "http://xmlns.com/foaf/0.1/")]
        public LiteralType[] name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rdvocab.info/ElementsGr2/")]
        public LiteralType biographicalInformation
        {
            get
            {
                return this.biographicalInformationField;
            }
            set
            {
                this.biographicalInformationField = value;
                this.RaisePropertyChanged("biographicalInformation");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rdvocab.info/ElementsGr2/")]
        public LiteralType dateOfBirth
        {
            get
            {
                return this.dateOfBirthField;
            }
            set
            {
                this.dateOfBirthField = value;
                this.RaisePropertyChanged("dateOfBirth");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rdvocab.info/ElementsGr2/")]
        public LiteralType dateOfDeath
        {
            get
            {
                return this.dateOfDeathField;
            }
            set
            {
                this.dateOfDeathField = value;
                this.RaisePropertyChanged("dateOfDeath");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rdvocab.info/ElementsGr2/")]
        public LiteralType dateOfEstablishment
        {
            get
            {
                return this.dateOfEstablishmentField;
            }
            set
            {
                this.dateOfEstablishmentField = value;
                this.RaisePropertyChanged("dateOfEstablishment");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rdvocab.info/ElementsGr2/")]
        public LiteralType dateOfTermination
        {
            get
            {
                return this.dateOfTerminationField;
            }
            set
            {
                this.dateOfTerminationField = value;
                this.RaisePropertyChanged("dateOfTermination");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rdvocab.info/ElementsGr2/")]
        public LiteralType gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
                this.RaisePropertyChanged("gender");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://rdvocab.info/ElementsGr2/")]
        public ResourceOrLiteralType professionOrOccupation
        {
            get
            {
                return this.professionOrOccupationField;
            }
            set
            {
                this.professionOrOccupationField = value;
                this.RaisePropertyChanged("professionOrOccupation");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sameAs", Namespace = "http://www.w3.org/2002/07/owl#")]
        public ResourceType[] sameAs
        {
            get
            {
                return this.sameAsField;
            }
            set
            {
                this.sameAsField = value;
                this.RaisePropertyChanged("sameAs");
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseProvidedCHOType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProvidedCHOType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.europeana.eu/schemas/edm/")]
    public partial class EuropeanaType : AboutType
    {

        private object[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contributor", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("coverage", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("creator", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("date", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("description", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("format", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("identifier", typeof(LiteralType), Namespace = "http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("language", typeof(LiteralType), Namespace = "http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("publisher", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("relation", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("rights", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("source", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("subject", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("title", typeof(LiteralType), Namespace = "http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("type", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/elements/1.1/")]
        [System.Xml.Serialization.XmlElementAttribute("alternative", typeof(LiteralType), Namespace = "http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("conformsTo", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("created", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("extent", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("hasFormat", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("hasPart", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("hasVersion", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("isFormatOf", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("isPartOf", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("isReferencedBy", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("isReplacedBy", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("isRequiredBy", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("isVersionOf", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("issued", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("medium", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("provenance", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("references", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("replaces", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("requires", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("spatial", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("tableOfContents", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlElementAttribute("temporal", typeof(ResourceOrLiteralType), Namespace = "http://purl.org/dc/terms/")]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
                this.RaisePropertyChanged("ItemsElementName");
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.europeana.eu/schemas/edm/", IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/elements/1.1/:contributor")]
        contributor,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/elements/1.1/:coverage")]
        coverage,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/elements/1.1/:creator")]
        creator,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/elements/1.1/:date")]
        date,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/elements/1.1/:description")]
        description,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/elements/1.1/:format")]
        format,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/elements/1.1/:identifier")]
        identifier,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/elements/1.1/:language")]
        language,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/elements/1.1/:publisher")]
        publisher,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/elements/1.1/:relation")]
        relation,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/elements/1.1/:rights")]
        rights,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/elements/1.1/:source")]
        source,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/elements/1.1/:subject")]
        subject,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/elements/1.1/:title")]
        title,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/elements/1.1/:type")]
        type,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/terms/:alternative")]
        alternative,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/terms/:conformsTo")]
        conformsTo,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/terms/:created")]
        created,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/terms/:extent")]
        extent,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/terms/:hasFormat")]
        hasFormat,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/terms/:hasPart")]
        hasPart,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/terms/:hasVersion")]
        hasVersion,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/terms/:isFormatOf")]
        isFormatOf,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/terms/:isPartOf")]
        isPartOf,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/terms/:isReferencedBy")]
        isReferencedBy,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/terms/:isReplacedBy")]
        isReplacedBy,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/terms/:isRequiredBy")]
        isRequiredBy,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/terms/:isVersionOf")]
        isVersionOf,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/terms/:issued")]
        issued,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/terms/:medium")]
        medium,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/terms/:provenance")]
        provenance,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/terms/:references")]
        references,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/terms/:replaces")]
        replaces,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/terms/:requires")]
        requires,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/terms/:spatial")]
        spatial,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/terms/:tableOfContents")]
        tableOfContents,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://purl.org/dc/terms/:temporal")]
        temporal,
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProvidedCHOType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.europeana.eu/schemas/edm/")]
    public partial class BaseProvidedCHOType : EuropeanaType
    {

        private ResourceType currentLocationField;

        private LiteralType[] hasMetField;

        private ResourceOrLiteralType[] hasTypeField;

        private ResourceType[] incorporatesField;

        private ResourceType[] isDerivativeOfField;

        private ResourceType isNextInSequenceField;

        private ResourceOrLiteralType[] isRelatedToField;

        private ResourceType isRepresentationOfField;

        private ResourceType[] isSimilarToField;

        private ResourceType[] isSuccessorOfField;

        private ResourceType[] realizesField;

        private EdmType typeField;

        /// <remarks/>
        public ResourceType currentLocation
        {
            get
            {
                return this.currentLocationField;
            }
            set
            {
                this.currentLocationField = value;
                this.RaisePropertyChanged("currentLocation");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("hasMet")]
        public LiteralType[] hasMet
        {
            get
            {
                return this.hasMetField;
            }
            set
            {
                this.hasMetField = value;
                this.RaisePropertyChanged("hasMet");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("hasType")]
        public ResourceOrLiteralType[] hasType
        {
            get
            {
                return this.hasTypeField;
            }
            set
            {
                this.hasTypeField = value;
                this.RaisePropertyChanged("hasType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("incorporates")]
        public ResourceType[] incorporates
        {
            get
            {
                return this.incorporatesField;
            }
            set
            {
                this.incorporatesField = value;
                this.RaisePropertyChanged("incorporates");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("isDerivativeOf")]
        public ResourceType[] isDerivativeOf
        {
            get
            {
                return this.isDerivativeOfField;
            }
            set
            {
                this.isDerivativeOfField = value;
                this.RaisePropertyChanged("isDerivativeOf");
            }
        }

        /// <remarks/>
        public ResourceType isNextInSequence
        {
            get
            {
                return this.isNextInSequenceField;
            }
            set
            {
                this.isNextInSequenceField = value;
                this.RaisePropertyChanged("isNextInSequence");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("isRelatedTo")]
        public ResourceOrLiteralType[] isRelatedTo
        {
            get
            {
                return this.isRelatedToField;
            }
            set
            {
                this.isRelatedToField = value;
                this.RaisePropertyChanged("isRelatedTo");
            }
        }

        /// <remarks/>
        public ResourceType isRepresentationOf
        {
            get
            {
                return this.isRepresentationOfField;
            }
            set
            {
                this.isRepresentationOfField = value;
                this.RaisePropertyChanged("isRepresentationOf");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("isSimilarTo")]
        public ResourceType[] isSimilarTo
        {
            get
            {
                return this.isSimilarToField;
            }
            set
            {
                this.isSimilarToField = value;
                this.RaisePropertyChanged("isSimilarTo");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("isSuccessorOf")]
        public ResourceType[] isSuccessorOf
        {
            get
            {
                return this.isSuccessorOfField;
            }
            set
            {
                this.isSuccessorOfField = value;
                this.RaisePropertyChanged("isSuccessorOf");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("realizes")]
        public ResourceType[] realizes
        {
            get
            {
                return this.realizesField;
            }
            set
            {
                this.realizesField = value;
                this.RaisePropertyChanged("realizes");
            }
        }

        /// <remarks/>
        public EdmType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.europeana.eu/schemas/edm/")]
    public enum EdmType
    {

        /// <remarks/>
        TEXT,

        /// <remarks/>
        VIDEO,

        /// <remarks/>
        IMAGE,

        /// <remarks/>
        SOUND,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3D")]
        Item3D,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.europeana.eu/schemas/edm/")]
    public partial class ProvidedCHOType : BaseProvidedCHOType
    {

        private ResourceType[] sameAsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sameAs", Namespace = "http://www.w3.org/2002/07/owl#")]
        public ResourceType[] sameAs
        {
            get
            {
                return this.sameAsField;
            }
            set
            {
                this.sameAsField = value;
                this.RaisePropertyChanged("sameAs");
            }
        }
    }
}
